"""
02_download_counts.py
─────────────────────
Downloads STAR raw count files from the GDC API for a cohort
defined in cohort_metadata.csv.

Usage
-----
    python 02_download_counts.py [--workers N] [--batch-size N] [--force]

    --workers    Number of parallel download threads (default: 8)
    --batch-size Files per API request             (default: 50)
    --force      Re-download files already on disk (default: False)

Input
-----
    cohort_metadata.csv   → generated by 01_build_cohort.ipynb

Output
------
    ./matrix_counts/      → directory with one folder per file_id,
                            each containing a .tsv count file
    download.log          → persistent log of all runs
"""

import requests
import io
import tarfile
import os
import logging
import argparse
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed

# ── Configuration ────────────────────────────────────────────
GDC_API     = "https://api.gdc.cancer.gov"
METADATA    = "cohort_metadata.csv"
OUTPUT_DIR  = "./matrix_counts"
BATCH_SIZE  = 50
MAX_WORKERS = 8
# ─────────────────────────────────────────────────────────────


def setup_logging(log_file: str = "download.log") -> logging.Logger:
    """Configure a logger that writes to both console and a log file."""
    logger = logging.getLogger("gdc_download")
    logger.setLevel(logging.DEBUG)

    fmt = logging.Formatter(
        "%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )

    # Console handler — INFO and above
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch.setFormatter(fmt)

    # File handler — DEBUG and above (keeps full trace for HPC jobs)
    fh = logging.FileHandler(log_file)
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(fmt)

    logger.addHandler(ch)
    logger.addHandler(fh)
    return logger


def is_already_downloaded(file_id: str, output_dir: str) -> bool:
    """
    Return True if file_id already has a folder with at least one .tsv
    (or .tsv.gz) file — safe to skip on resume.
    """
    folder = os.path.join(output_dir, file_id)
    if not os.path.isdir(folder):
        return False
    return any(
        f.endswith(".tsv") or f.endswith(".tsv.gz")
        for f in os.listdir(folder)
    )


def download_batch(
    file_ids: list,
    output_dir: str,
    logger: logging.Logger
) -> tuple[list, list]:
    """
    Download a batch of GDC files as tar.gz and extract in-place.

    Returns
    -------
    ok      : list of file_ids successfully downloaded
    failed  : list of file_ids that raised an exception
    """
    os.makedirs(output_dir, exist_ok=True)

    try:
        r = requests.post(
            f"{GDC_API}/data",
            json={"ids": file_ids},
            stream=True,
            timeout=300
        )
        r.raise_for_status()

        content_type = r.headers.get("Content-Type", "")

        if "tar" in content_type or len(file_ids) > 1:
            buf = io.BytesIO()
            for chunk in r.iter_content(chunk_size=8192):
                buf.write(chunk)
            buf.seek(0)
            with tarfile.open(fileobj=buf, mode="r:gz") as tar:
                tar.extractall(path=output_dir)
        else:
            fpath = os.path.join(output_dir, file_ids[0] + ".tsv.gz")
            with open(fpath, "wb") as fh:
                for chunk in r.iter_content(chunk_size=8192):
                    fh.write(chunk)

        logger.debug(f"Batch OK — {len(file_ids)} files: {file_ids[:3]}{'...' if len(file_ids) > 3 else ''}")
        return file_ids, []

    except Exception as e:
        logger.warning(f"Batch FAILED ({len(file_ids)} files): {e}")
        return [], file_ids


def download_all(
    df: pd.DataFrame,
    output_dir: str = OUTPUT_DIR,
    batch_size: int = BATCH_SIZE,
    max_workers: int = MAX_WORKERS,
    force: bool = False,
    logger: logging.Logger = None
) -> None:
    """
    Download all files in parallel batches.

    Parameters
    ----------
    df          : metadata DataFrame with a 'file_id' column
    output_dir  : destination directory
    batch_size  : number of file IDs per GDC API request
    max_workers : number of concurrent download threads
    force       : if False, skip files already present on disk
    logger      : configured Logger instance
    """
    if logger is None:
        logger = logging.getLogger("gdc_download")

    all_ids = df["file_id"].tolist()

    # ── Resume: filter out already-downloaded files ───────────
    if not force:
        pending = [fid for fid in all_ids
                   if not is_already_downloaded(fid, output_dir)]
        skipped = len(all_ids) - len(pending)
        if skipped:
            logger.info(f"Skipping {skipped} already-downloaded files "
                        f"(use --force to re-download)")
    else:
        pending = all_ids

    if not pending:
        logger.info("All files already downloaded. Nothing to do.")
        return

    batches = [pending[i:i + batch_size]
               for i in range(0, len(pending), batch_size)]

    logger.info(
        f"Downloading {len(pending)}/{len(all_ids)} files | "
        f"{len(batches)} batches | {max_workers} workers → {output_dir}"
    )

    ok_total     = 0
    failed_total = []

    # ── Parallel execution ────────────────────────────────────
    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {
            pool.submit(download_batch, batch, output_dir, logger): batch
            for batch in batches
        }

        for i, future in enumerate(as_completed(futures), 1):
            ok, failed = future.result()
            ok_total     += len(ok)
            failed_total += failed

            pct = 100 * i / len(batches)
            logger.info(
                f"Progress: {i}/{len(batches)} batches "
                f"({pct:.0f}%)  |  "
                f"OK: {ok_total}  Failed: {len(failed_total)}"
            )

    # ── Final summary ─────────────────────────────────────────
    logger.info("=" * 55)
    logger.info(f"Download complete.")
    logger.info(f"  Successfully downloaded : {ok_total} files")
    if failed_total:
        logger.warning(f"  Failed                  : {len(failed_total)} files")
        logger.warning(f"  Failed IDs: {failed_total}")
        logger.warning("  Re-run the script to retry — already-downloaded "
                       "files will be skipped automatically.")
    else:
        logger.info("  Failed                  : 0 files")
    logger.info("=" * 55)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Download GDC STAR count files in parallel."
    )
    parser.add_argument(
        "--workers", type=int, default=MAX_WORKERS,
        help=f"Parallel download threads (default: {MAX_WORKERS})"
    )
    parser.add_argument(
        "--batch-size", type=int, default=BATCH_SIZE,
        help=f"Files per API request (default: {BATCH_SIZE})"
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Re-download files already on disk"
    )
    args = parser.parse_args()

    logger = setup_logging("download.log")
    logger.info(f"Loading metadata from {METADATA}...")
    df_selected = pd.read_csv(METADATA)
    logger.info(f"  {len(df_selected)} samples found")

    download_all(
        df_selected,
        output_dir  = OUTPUT_DIR,
        batch_size  = args.batch_size,
        max_workers = args.workers,
        force       = args.force,
        logger      = logger
    )
