"""
03_build_count_matrix.py
────────────────────────
Reads STAR raw count .tsv files downloaded by 02_download_counts.py
and assembles a genes x samples count matrix.

Usage
-----
    python 03_build_count_matrix.py [--save-csv]

    --save-csv   Also write counts_matrix.csv.gz in addition to parquet
                 (slower/larger; useful if downstream tools can't read parquet)

Input
-----
    cohort_metadata.csv   → generated by 01_cohort_construction.ipynb
    ./matrix_counts/      → generated by 02_download_counts.py

Output
------
    counts_matrix.parquet → genes x samples count matrix
    counts_matrix.csv.gz  → (optional) same matrix as compressed CSV
    labels.csv            → mutation and clinical labels aligned to
                            count matrix columns
"""

import os
import argparse
import pandas as pd

# ── Configuration ────────────────────────────────────────────
METADATA       = "cohort_metadata.csv"
DATA_DIR       = "./matrix_counts"
OUT_MATRIX     = "counts_matrix.parquet"
OUT_MATRIX_CSV = "counts_matrix.csv.gz"
OUT_LABELS     = "labels.csv"
# ─────────────────────────────────────────────────────────────


def detect_mutated_genes(df_meta: pd.DataFrame) -> list:
    """
    Auto-detect per-gene mutation columns written by 01_build_cohort.ipynb.
    Returns a list of gene symbols inferred from 'mut_<GENE>' column names.
    This avoids having to manually keep MUTATED_GENES in sync across scripts.

    Example: columns ['mut_EGFR', 'mut_KRAS'] → ['EGFR', 'KRAS']
    """
    genes = [
        col[4:]                     # strip the 'mut_' prefix
        for col in df_meta.columns
        if col.startswith("mut_")
    ]
    if genes:
        print(f"  Auto-detected mutation columns for: {genes}")
    else:
        print("  No per-gene mutation columns found in metadata.")
    return genes


def build_count_matrix(
    df_meta: pd.DataFrame,
    data_dir: str = DATA_DIR
) -> pd.DataFrame:
    """
    Read STAR count .tsv files and build a genes x samples DataFrame.
    Removes STAR summary rows (N_unmapped, N_multimapping, etc.).

    Prints progress every 50 samples so long runs stay observable.

    Parameters
    ----------
    df_meta  : DataFrame with at least file_id and submitter_id columns
    data_dir : path to the directory containing downloaded count folders

    Returns
    -------
    DataFrame of shape (n_genes, n_samples)
    """
    dfs     = []
    missing = []
    total   = len(df_meta)

    for i, (_, row) in enumerate(df_meta.iterrows(), 1):
        fid    = row["file_id"]
        label  = row["submitter_id"]
        folder = os.path.join(data_dir, fid)

        if not os.path.isdir(folder):
            missing.append(fid)
            continue

        tsv_files = [f for f in os.listdir(folder)
                     if f.endswith(".tsv") or f.endswith(".tsv.gz")]
        if not tsv_files:
            missing.append(fid)
            continue

        tsv_path = os.path.join(folder, tsv_files[0])
        tmp = pd.read_csv(
            tsv_path, sep="\t", comment="#",
            usecols=["gene_id", "unstranded"],
            index_col="gene_id"
        )

        # Remove STAR summary rows (lines starting with N_)
        tmp = tmp[~tmp.index.str.startswith("N_")]
        tmp.columns = [label]
        dfs.append(tmp)

        # Progress reporting every 50 samples
        if i % 50 == 0 or i == total:
            found = i - len(missing)
            print(f"  [{i}/{total}] Loaded {found} samples, "
                  f"{len(missing)} missing so far...")

    # ── Integrity warning ─────────────────────────────────────
    if missing:
        print(f"\n  ⚠  Warning: {len(missing)} file(s) not found locally "
              f"— excluded from matrix.")
        print(f"     Missing file_ids: {missing[:10]}"
              f"{'  (+more)' if len(missing) > 10 else ''}")
        print("     Re-run 02_download_counts.py to fetch missing files.")

    if not dfs:
        raise RuntimeError(
            "No count files could be loaded. "
            "Check DATA_DIR and that 02_download_counts.py ran successfully."
        )

    matrix = pd.concat(dfs, axis=1)
    print(f"\n  Count matrix: {matrix.shape[0]:,} genes × "
          f"{matrix.shape[1]:,} samples")
    return matrix


def save_labels(
    df_meta: pd.DataFrame,
    counts: pd.DataFrame,
    mutated_genes: list,
    out_path: str = OUT_LABELS
) -> None:
    """
    Save mutation and clinical labels aligned to count matrix columns.

    Parameters
    ----------
    df_meta       : full metadata DataFrame
    counts        : count matrix (columns = submitter_ids)
    mutated_genes : list of gene symbols (auto-detected from metadata)
    out_path      : output CSV path
    """
    label_cols = (
        [col for col in df_meta.columns
         if col.startswith("mutated_")]          # e.g. mutated_any
        + [f"mut_{g}" for g in mutated_genes]    # e.g. mut_EGFR, mut_KRAS
        + ["tobacco_smoking", "stage",
           "vital_status", "gender"]
    )

    # Keep only columns that actually exist in df_meta
    label_cols = [c for c in label_cols if c in df_meta.columns]

    labels = (
        df_meta.set_index("submitter_id")[label_cols]
               .reindex(counts.columns)
    )

    # Warn if any samples in the matrix have no metadata match
    unmatched = labels.index[labels.isnull().all(axis=1)].tolist()
    if unmatched:
        print(f"  ⚠  Warning: {len(unmatched)} sample(s) in the count "
              f"matrix have no metadata row.")

    labels.to_csv(out_path)
    print(f"  Labels saved → {out_path}  "
          f"({len(label_cols)} label columns)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Build a gene x sample count matrix from GDC STAR files."
    )
    parser.add_argument(
        "--save-csv", action="store_true",
        help="Also write counts_matrix.csv.gz (in addition to parquet)"
    )
    args = parser.parse_args()

    print(f"Loading metadata from {METADATA}...")
    df_meta = pd.read_csv(METADATA)
    print(f"  {len(df_meta)} samples found")

    # Auto-detect mutation gene list from metadata columns
    mutated_genes = detect_mutated_genes(df_meta)

    print("\nBuilding count matrix...")
    counts = build_count_matrix(df_meta, data_dir=DATA_DIR)

    print("\nSaving count matrix...")
    counts.to_parquet(OUT_MATRIX)
    print(f"  Saved → {OUT_MATRIX}")

    if args.save_csv:
        counts.to_csv(OUT_MATRIX_CSV, compression="gzip")
        print(f"  Saved → {OUT_MATRIX_CSV}")

    print("\nSaving labels...")
    save_labels(df_meta, counts, mutated_genes, out_path=OUT_LABELS)

    print("\nDone.")
